### ISSUE TITLE
Scrolling and New Pages

### ISSUE THREAD

**Issue by ghost** [tranxuanthang/villain3ds#12]
When scrolling to a new page in the application, it doesn't start from the top, it starts from wherever you where in the last page.

**Comment by tranxuanthang** [comment]
This issue is fixed in latest commit and new version will go out soon!
![villain3ds-v0.1.2](https://thumbs.gfycat.com/AdoredMeatyAphid-size_restricted.gif)
https://gfycat.com/gifs/detail/AdoredMeatyAphid
