### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by MWFIAE** [tranxuanthang/villain3ds#13]
Hey there, 

"Can't get make_cdn_cia for your OS (Error: self signed certificate in certificate chain).
Some requirements can't be acquired. The application will not continue until those requirements is fulfilled."

Well the error is true, since I'm in a corporate environment with an ssl sniffer in the middle that messes with the certificates. My question would be if it is possible to ignore that error (or make a warning popup or something if security is a concern for you).

Thanks in advance :)

**Comment by MWFIAE** [comment]
Seems like retrying works though. 
But maybe you will look into this as very low priority error   :)

(I will reply again if there are any further errors down the line) 

€: Errors further down the line ^^" 
It hasn't downloaded make_cdn_cia.exe (file existed with 0 Bytes). But hasn't reported an error, just kind of hangs with doing nothing.

**Comment by tranxuanthang** [comment]
A zero-bytes make_cdn_cia.exe is weird, in newest version the app should have detected 0 byte downloaded file and deleted it right away.
Anyways, for now workaround is that you manually download the make_cdn_cia.exe file on this github and put it into appropriate folder. It's like one-time download so you won't have to bother with it anymore.
I'll see what I can do about this certificate problem, no guarantee though.

**Comment by MWFIAE** [comment]
Yeah After I searched for the file on Google I realised it was in the github and manually replaced it already :) 

Thanks for the effort

**Comment by tranxuanthang** [comment]
There is a workaround I found to ignore the "self signed certificate..." error: by adding
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`
before the request. I'll add it in next versions if you still want it.

**Comment by MWFIAE** [comment]
It doesn't matter much to me anymore (except for Updates) but it may be a good Feature for others)
