### ISSUE TITLE
Decryted roms

### ISSUE THREAD

**Issue by Baldyshugga** [tranxuanthang/villain3ds#17]
Add in the ability to decrypt roms for use with Citra.

**Comment by tranxuanthang** [comment]
When summer comes I'll continue developing Villain3ds and more features will come soon. In the meanwhile you can try Wii U USB Maker, it is doing this job pretty good.

**Comment by scalp42** [comment]
@tranxuanthang commonkey.bin and disckey.bin don't apply here though?

**Comment by tranxuanthang** [comment]
@scalp42 Do you mean the key used in decryption feature in villain3ds v0.2.0 update?

**Comment by tranxuanthang** [comment]
From v0.2.0 there is a experiment decrypt feature for citra, but only support game title (not update & dlc) for now.

**Comment by karanrajpal14** [comment]
@tranxuanthang I did try decrypting a couple of ROMs but nothing seems to work. I start the process and it says that it's executing but even after a couple of hours nothing changes. Any idea what's up? How can I provide some logs that would help you?

**Comment by tranxuanthang** [comment]
There is a developer tool if you click "view" on menubar, so you can try going there and look if there is any exception. If you really need the decrypt right now, search for *decrypt_v2* file in some Chinese file in Google. Also I heard that there are some version of citra have support for running encrypted rom backup too.

**Comment by karanrajpal14** [comment]
Thank you! I'll post some logs when I try this again on Villian. And thanks for pointing me in the right direction. While I did not find "decrypt_v2" as it was on too many sites of various sizes, I did, however, find something called Batch CIA 3DS decryptor which works just fine.

Also, I couldn't find anything pertaining to those citra builds that you mentioned.
