### ISSUE TITLE
search not working ?

### ISSUE THREAD

**Issue by ntchris** [tranxuanthang/villain3ds#18]
Thanks for the super great tool.

Enter "detective" or "Detective" in search bar, no "detective pikachu" game is found.
However, if simply click on "popular" button, then the detective pikachu is right there.
but I checked many other keywords work fine, like mario, zelda ...
Thanks!

**Comment by tranxuanthang** [comment]
Just fixed it. It's a mistake in my backend, any recently added titles are not indexed in search dictionary. So those titles are unable to be found in search results.

**Comment by ntchris** [comment]
Great!! thanks a lot !!
Yes I can confirm its working well now.
