### ISSUE TITLE
oops something went wrong

### ISSUE THREAD

**Issue by threepoint2** [tranxuanthang/villain3ds#19]
Getting this generic error on both Mac and Windows versions.  Is there a log file generated or is this something broader?

**Comment by tranxuanthang** [comment]
My domain for villain3ds's backend processing is expired a few hours ago. Now I'm going to purchase my new domain (for some reasons I don't like my currently used domain so much so I'm not going to keep it). I'm sorry I didn't do this sooner, I'm still choosing a new domain name. :( A new update will be required to fix this error and any older versions will not be working anymore.

**Comment by threepoint2** [comment]
I appreciate the update and look forward to the future releases.

**Comment by tranxuanthang** [comment]
Check out my new release v0.1.3-2
https://github.com/tranxuanthang/villain3ds/releases
