### ISSUE TITLE
Stop compiling Villain3DS against GTK+ 3.

### ISSUE THREAD

**Issue by ghost** [tranxuanthang/villain3ds#20]
The Linux version of your latest version of Villain3DS now demands GTK+ 3 and the old version from January stopped working. This is bad.
GTK3 is not an upgrade from GTK2. It is a bastardization. Also, it depends on D-Bus/`systemd`.
https://igurublog.wordpress.com/2012/11/05/gnome-et-al-rotting-in-threes/
Please consider. You should make the program self-contained. I do not mind including seperate GTK3 ".so" files, but I mind that now you demand some particular system configurations.Minimal WMs are still a thing and you should not expect that everyone is using a full-featured DE like GNOME.

**Comment by tranxuanthang** [comment]
I'll see what I can do about it. This is pretty much the choice of Electron or Chromium Project, not me. So in worst case you might need to build a custom Villain3ds version for yourself with an older version of Electron that doesn't depend on GTK3.
Update: Chromium 61 is now using GTK3, therefore from electron v2.0.0 (which is based on Chromium 61), it switched to GTK+ 3 too. Building with electron v1.8.7 may fix your issue for now. Remember that Villain3ds is based on Electron so I can do little about this problem.

**Comment by ghost** [comment]
My idea is that you can fix the URL in your previous GTK+ 2 version to make it work, or make the URLs (hosts etc.) configurable.
Another option is to develop a ncurses version that can be run in CMD/Terminal, or make it a batch file/shell script.

**Comment by tranxuanthang** [comment]
If you're there check out this version. I rebuilt it with older version of Electron.
https://github.com/tranxuanthang/villain3ds/releases/tag/v0.1.3-3
A CLI version is a good idea. I'll try to do one when I have free time.
