### ISSUE TITLE
[Feature Request] Content Integrity Verifier

### ISSUE THREAD

**Issue by el-duderino5** [tranxuanthang/villain3ds#21]
Wii U USB Helper had the functionality of verifying the downloaded contents against the source. Would it be possible to add this feature to this application as well to avoid having corrupted CIAs due to network errors or other errors that may cause any content part to be corrupted?

**Comment by tranxuanthang** [comment]
We can verify downloaded content parts with hashes included in tmd file from CDN, but the content parts must be decrypted before. I'll research it further when summer break comes.
Remember that FBI already had the function to check & detect corrupted cias, so it can avoid any damage to your 3ds.

**Comment by el-duderino5** [comment]
Yeah, but I think it is more efficient to have Villain3DS detect inconsistencies in the integrity of the contents it downloads than downloading a corrupt file, copying it to the SD card, and then having FBI go through the process of installing the content, which may take a considerable amount of time (one, for copying the title to the SD card + the time it takes FBI to install the title), which grows as the size of the title gets bigger. 

Imagine if you were to install the whole 3GB of Resident Evil Revelations: you'd have to copy it first to the SD card, which takes about 30 minutes in my case because I'm on USB 2.0, and then about the same amount of time (more or less) for FBI to install the title, only to get an error near the end of the installation (worst case scenario). Or are you talking about another function of FBI that verifies the integrity of a title before it actually installs it? Because all I use it for is CIA and titlekey installation, and occasionally ticket deletion.

Is that function you are talking about part of the CIA installation process or a separate function of FBI?

**Comment by tranxuanthang** [comment]
What you said is true. About details how FBI check file cia file, before or while or after installation, I don't really know or remember.

**Comment by tranxuanthang** [comment]
I think I found some ways to verify downloaded contents. First the ncch files (content files) must be decrypted with the title key (fuse-3ds integration is a lazy way to to this, but users need to install additional software like winfsp, and I think there should be other ways). Then we must calculate and compare the SHA-256 hashes of each files with the string inside "tmd" file. If the checksum is match then we can be sure the content is 100% valid.
Beware that it's will not be a quick and easy process, especially with very large content files (1GB+).

**Comment by el-duderino5** [comment]
Closing this ticket as the function is now implemented.
