### ISSUE TITLE
Some titles are not complete

### ISSUE THREAD

**Issue by el-duderino5** [tranxuanthang/villain3ds#22]
As an example to illustrate what I mean by this, I will mention the Fire Emblem Echoes: Shadows of Valentia DLC. I downloaded this with Wii U USB Helper and the size is around 427MB. When I looked up this same title on Villain3DS, it says the DLC is only 68.2MB in size.

This DLC in specific, is not complete at all. It is missing data. I suspect the same thing may be happening to other titles. @tranxuanthang , do you have an idea why this may be happening?

Using the latest Villain3DS on Linux, btw.

**Comment by tranxuanthang** [comment]
Don't trust the DLC size showed in home/detail page. Try downloading it and see if downloaded cia has the same size as WiiU Usb Helper or not.

**Comment by el-duderino5** [comment]
I followed your advice, and both the DLC gotten from Wii U USB Helper and Villain3DS have the same size, so I guess what you said is correct. Hopefully though, whenever you have the time and motivation to fix the information presented to the user (in this case, the size of a content) you can do so.

I'm going to go ahead and close this. Good luck with this project and I hope you continue to improve Villain3DS. I like it very much :)
