### ISSUE TITLE
SHA-256 hash mismatch 50+% of the time in all downloads, requires redownload

### ISSUE THREAD

**Issue by chrisfand** [tranxuanthang/villain3ds#24]
#21 I keep getting hash mismatch errors very often when a download completes. I have to restart the download when that happens. Definitely the biggest issue so far.

![error](https://user-images.githubusercontent.com/3870029/42256257-36ba2490-7f1e-11e8-934e-614b0589184a.png)

**Comment by c62624** [comment]
#21

**Comment by tranxuanthang** [comment]
I'm looking into it now. Also what is your operating system?

I tried downloading your title (mario golf world tour) and it downloaded successfully. It has following hash:
cID 00000003: 8ba69cfce4d2fb4f77120ee1acf5bf467f3076f384e6c5c2115abdd63eb2aed9

So I don't think it was the hash feature which was wrong. Something makes you keep downloading corrupted files.

To be sure I need some more information. For example the hash of `~/Villain3DS/raw/00040000000dcd00/00000003` file after it was completed downloading. But maybe this file is deleted as soon as a hash mismatch is detected, so a custom build of Villain3DS might be needed to do it.

**Comment by chrisfand** [comment]
Windows 10 64 bit

I was downloading to an external usb 3.0 hard drive and it was corrupting often though that drive hasn't given me problems in anything else.

I started downloading it on my OS SSD and it drastically reduced the rate it happened. Seems like it's only likely to occur now if downloading multiple titles at once.

**Comment by tranxuanthang** [comment]
Removable drives are usually less reliable than internal hdd/ssd. Right now all I can say is that you should download to your any internal hdd/ssd then copy your files later. Maybe because of some reasons the multi-thread downloader module I used or nodeJS's file system API doesn't play nice with your drive.

**Comment by Nomelas** [comment]
I have the same problem. tried running on both my OS's ssd drive, and also my internal hdd - same issue. some files constantly have mismatched SHA-256,

**Comment by tranxuanthang** [comment]
I think it is fixed (temporary) in v0.2.1. More info here: https://gbatemp.net/threads/release-villain3ds-basically-freeshop-but-runs-on-your-pc.488127/page-23#post-8196595
