### ISSUE TITLE
Title Keys not matching

### ISSUE THREAD

**Issue by leonjmagnus** [tranxuanthang/villain3ds#26]
I noticed that while using the same title keys bin I see games that display on that one shop but doesn't display on search results for this app.

One example is the newly released Etrian Odyssey X (世界樹の迷宮X)

**Comment by tranxuanthang** [comment]
I still have to manually update the database each time there are new titles added, so sometimes newly added titles are missing. Anyways check it again, I think it should be there now.

**Comment by leonjmagnus** [comment]
Sorry, didn't know it was a manual process. Thanks for your work!
