### ISSUE TITLE
Error to convert some DLC to CIA file

### ISSUE THREAD

**Issue by beeGod** [tranxuanthang/villain3ds#7]
There's something failing at the time it try to write the final CIA file for some DLC.

It happened to me with two DLC. The first one I can't remember now, but the second one was with "FE ESoV DLC" (full name at the screeshot). The program downloaded all the files properly, and output the success message for convert and rename the final file, it even deleted the folder for the downloaded RAW files, but the final CIA file stays with zero Kb size.

I already tried to redownload all over again, and it keeps with error.

![ss](https://user-images.githubusercontent.com/4568068/33683137-03ec126a-dab1-11e7-9997-6380964e6d91.png)

**Comment by tranxuanthang** [comment]
This is what happened when manually running the make_cdn_cia command. Strange, it just crashes and leaves no error output.
![Pic](https://i.imgur.com/E79vlJO.png)

**Comment by beeGod** [comment]
Adding, I noticed that the file size for this DLC at the menu list isn't the total sum of all files downloaded.

**Comment by beeGod** [comment]
@tranxuanthang Then the only solution is to wait and try a new release for the make_cdn_cia. Their project github have no ISSUES menu for third ones to feedback.

**Comment by tranxuanthang** [comment]
It's possible that Villain3DS download the wrong files or something. I'll try downloading this dlc with Funkeycia, CDN-FX, Wii U Usb Helper,.. and see if they face similar problem.

**Comment by tranxuanthang** [comment]
Funkeycia get the same issue. Only Usb Helper still generates the cia file successfully.
![Imgur](https://i.imgur.com/k96HftR.png)

**Comment by tranxuanthang** [comment]
This version of make_cdn_cia seems to work:
https://github.com/YodaDaCoda/make_cdn_cia
I compiled the source and tested the new binary file on linux. No console output, but no crashes, a 427,1MB file (Fire Emblem™ Echoes Shadows of Valentia USA (0004008c001b4000).cia) is generated. I haven't tested the cia yet.

**Comment by tranxuanthang** [comment]
Fixed in 0.1.2 with new make_cdn_cia binary (hopefully)
