### ISSUE TITLE
Sometimes the program fails to convert RAW to CIA

### ISSUE THREAD

**Issue by beeGod** [tranxuanthang/villain3ds#8]
It happened about 3 or 4 times now. The download of RAW files run properly, and it output the success message of convert and renaming files to the final CIA file, but the file is created with zero Kb and, differently from the issue#7, the RAW files remains at the RAW folder (what, I suppose, would be deleted if everything was ok at the end).

Easily solved by redownloading the game or update from the beggining.

**Comment by tranxuanthang** [comment]
This is what happened when manually running the make_cdn_cia command. Strange, it just crashes and leaves no error output.
![Pic](https://i.imgur.com/E79vlJO.png)

**Comment by tranxuanthang** [comment]
Now there are many changes around the make CIA part of the program, from when this issue was first posted. It now shows the size of generated CIA and many other things and fixes. So allow me to close this issue.
